source = ~/.config/omarchy/current/theme/hyprlock.conf

general {
    ignore_empty_input = true
}

background {
    monitor =
    color = $color
    path = ~/.config/omarchy/current/background
    blur_passes = 3
}

animations {
    enabled = false
}

label {
    monitor =
    text = $TIME
    color = $font_color
    font_family = JetBrainsMono Nerd Font
    font_size = 90
    position = 0, 200
    halign = center
    valign = center
    shadow_color = rgba(0, 0, 0, 0.35)
}

label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B"
    color = $font_color
    font_family = JetBrainsMono Nerd Font
    font_size = 24
    position = 0, 100
    halign = center
    valign = center
    shadow_color = rgba(0, 0, 0, 0.30)
}

label {
    monitor =
    text = $FPRINTPROMPT
    color = $check_color
    font_family = JetBrainsMono Nerd Font
    font_size = 13
    position = 0, -72
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 500, 80
    position = 0, 0
    halign = center
    valign = center

    inner_color = $inner_color
    outer_color = $outer_color
    outline_thickness = 2

    font_family = JetBrainsMono Nerd Font
    font_color = $font_color

    placeholder_text = Enter Password
    check_color = $check_color
    fail_text = <i>$FAIL ($ATTEMPTS)</i>

    rounding = 6
    shadow_passes = 0
    fade_on_empty = false
}

auth {
    fingerprint:enabled = true
}
